	--------------【声明全局变量】--------------
	modimport("scripts/rp_language")
	
	--------------【获取设置页面的值】--------------
	GLOBAL.GAME_LANGUAGE = GetModConfigData("language")
	
	--游戏中一天的时间（秒）
	GLOBAL.GAME_DAY = GLOBAL.TUNING.TOTAL_DAY_TIME
	
	--怪物开始被安置的时间
	GLOBAL.MONSTER_START_POINT_DAY = 1
	--开始普通入侵的时间
	GLOBAL.MONSTER_INVADE_DAY= 1
	--开始猪王入侵的时间
	GLOBAL.MONSTER_PIGKING_INVADE_DAY= 1
	
	--进攻怪物类型
	GLOBAL.INVASIVE_MOB = 1
	GLOBAL.INVASIVE_COMMANDER = 2
	GLOBAL.INVASIVE_KING = 3
	
	--防御怪物类型
	GLOBAL.DEFENSIVE_MOB = 4
	GLOBAL.DEFENSIVE_COMMANDER = 5
	GLOBAL.DEFENSIVE_KING = 6
	
	--boss复活时间(秒)
	GLOBAL.BOSS_REVIVE_TIME = 20
	
	--怪物名称
	GLOBAL.PIGMANBOSS_NAME = STRING_PIGMANBOSS_NAME
	GLOBAL.BUNNYMAN_KING_NAME = STRING_BUNNYMAN_KING_NAME
	GLOBAL.MERM_KING_NAME = STRING_MERM_KING_NAME
	GLOBAL.ROCKY_KING_NAME = STRING_ROCKY_KING_NAME
	GLOBAL.PIGBROTHER_NAME = STRING_PIGBROTHER_NAME
	GLOBAL.BIG_PIGBROTHER_NAME = STRING_BIG_PIGBROTHER_NAME 
	GLOBAL.LITTLE_PIGBROTHER_NAME = STRING_LITTLE_PIGBROTHER_NAME
	GLOBAL.LEIF_KING_NAME = STRING_LEIF_KING_NAME
	
	--兔人boss相关
	GLOBAL.BUNNYMAN_HEALTH = 200--兔人boss生命值
	GLOBAL.BUNNYMAN_HYPONSIS_COOLDOWN = 8 --催眠冷却时间
	GLOBAL.BUNNYMAN_LIGHTING_COOLDOWN = 8 --落雷冷却时间
	GLOBAL.BUNNYMAN_HYPONSIS_RANGE = 20 --催眠范围
	GLOBAL.BUNNYMAN_LIGHTING_RANGE = 8 --落雷范围
	
	--鱼人boss相关
	GLOBAL.MERM_HEALTH = 200--鱼人boss生命值
	GLOBAL.MERM_TOGGLE_COOLDOWN = 8 --鱼人攻击方式转变时间
	
	--石虾boss相关
	GLOBAL.ROCKY_HEALTH = 200--石虾boss生命值 
	--GLOBAL.ROCKY_GROUNDPOUND_COOLDOWN = 5 --拍地板冷却时间
	GLOBAL.ROCKY_CALLMETEOR_COOLDOWN = 8 --召唤流星雨冷却时间
	
	--野猪兄弟boss相关
	GLOBAL.LITTLE_PIGBROTHER_HEALTH = 200--小野猪boss生命值
	GLOBAL.BIG_PIGBROTHER_HEALTH = 200 --大野猪boss生命值 	
	
	--树人boss相关
	GLOBAL.LEIF_HEALTH = 200
	GLOBAL.LEIF_EARTHQUACK_COOLDOWN = 6 --大地颤怒冷却时间
	--GLOBAL.LEIF_ROOTTHORN_COOLDOWN = 2 
	
	--猪人boss相关
	GLOBAL.PIGMAN_HEALTH = 200
	
	--系统宣告语
	GLOBAL.ANNOUNCE_SPEECH_1 = STRING_ANNOUNCE_SPEECH_1
	GLOBAL.ANNOUNCE_SPEECH_2 = STRING_ANNOUNCE_SPEECH_2
	GLOBAL.ANNOUNCE_SPEECH_3_1 = STRING_ANNOUNCE_SPEECH_3_1
	GLOBAL.ANNOUNCE_SPEECH_3_2 = STRING_ANNOUNCE_SPEECH_3_2
	GLOBAL.ANNOUNCE_SPEECH_4_1 = STRING_ANNOUNCE_SPEECH_4_1
	GLOBAL.ANNOUNCE_SPEECH_4_2 = STRING_ANNOUNCE_SPEECH_4_2
	GLOBAL.ANNOUNCE_SPEECH_5_1 = STRING_ANNOUNCE_SPEECH_5_1
	GLOBAL.ANNOUNCE_SPEECH_5_2 = STRING_ANNOUNCE_SPEECH_5_2
	GLOBAL.ANNOUNCE_SPEECH_5_3 = STRING_ANNOUNCE_SPEECH_5_3
	GLOBAL.ANNOUNCE_SPEECH_5_4 = STRING_ANNOUNCE_SPEECH_5_4
	GLOBAL.ANNOUNCE_SPEECH_6 = STRING_ANNOUNCE_SPEECH_6
	GLOBAL.ANNOUNCE_SPEECH_7 = STRING_ANNOUNCE_SPEECH_7
	GLOBAL.ANNOUNCE_SPEECH_8 = STRING_ANNOUNCE_SPEECH_8
	